packages:
  - .

overrides:
  ajv@<6.14.0: ">=6.14.0"
  brace-expansion@<1.1.13: ">=1.1.13"
  brace-expansion@>=2.0.0 <2.0.3: ">=2.0.3"
  fast-uri@<=3.1.0: ">=3.1.1"
  fast-uri@<=3.1.1: ">=3.1.2"
  flatted@<3.4.0: ">=3.4.0"
  flatted@<=3.4.1: ">=3.4.2"
  minimatch@<3.1.3: ">=3.1.3"
  minimatch@<3.1.4: ">=3.1.4"
  minimatch@>=9.0.0 <9.0.6: ">=9.0.6"
  minimatch@>=9.0.0 <9.0.7: ">=9.0.7"
  postcss@<8.5.10: ">=8.5.10"
  socket.io-parser@>=4.0.0 <4.2.6: ">=4.2.6"
  ws@>=8.0.0 <8.20.1: ">=8.20.1"

onlyBuiltDependencies:
  - esbuild
